[[classes]]
name = "class1"
children = [
    "class2"
]

[[classes]]
name = "class2"
parent = "class1"
variables = { var1 = "int", var2 = "float" }
methods = [
    "method1", 
    "method2"
]

[[methods]]
name = "method1"
class = "class2"
parameters = { param1 = "int", param2 = "float" }
returns = "int"

[[methods]]
name = "method2"
class = "class2"
calls = [
    "class2:method1",
    "function1"
]

[[functions]]
name = "function1"

[[functions]]
name = "function2"
parameters = { param1 = "int", param2 = "float" }
calls = [
    "function1",
    "class2:method2"
]
returns = "int"